language: rust
sudo: false

cache: cargo

branches:
  only:
    - master
    - /^test-.*$/

matrix:
  include:
    - language: node_js
      os: linux
      node_js:
        - 'node'
        - '11'
        - '10'
        - '9'
        - '8'
      before_install:
        - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
        - sh /tmp/rustup.sh -y
        - export PATH="$HOME/.cargo/bin:$PATH"
        - source "$HOME/.cargo/env"
        - node -v
        - npm -v
        - npm install
      script:
        - npm test
    - language: node_js
      os: osx
      node_js:
        - 'node'
        - '11'
        - '10'
        - '9'
        - '8'
      before_install:
        - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
        - sh /tmp/rustup.sh -y
        - export PATH="$HOME/.cargo/bin:$PATH"
        - source "$HOME/.cargo/env"
        - node -v
        - npm -v
        - npm install
      script:
        - npm test