os:
  - osx
  - linux
  - windows

language: rust
sudo: false

cache: cargo

branches:
  only:
    - master
    - /^test-.*$/

matrix:
  include:
    - language: node_js
      node_js:
        - 'node'
        - '11'
        - '10'
        - '9'
        - '8'
      before_install:
        - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
        - sh /tmp/rustup.sh -y
        - export PATH="$HOME/.cargo/bin:$PATH"
        - source "$HOME/.cargo/env"
        - node -v
        - npm -v
        - cd nodejs
        - npm install
      script:
        - npm test
        - ln -s ./node_modules/@amilajack/node-pre-gyp/bin/node-pre-gyp &&  -s ./node_modules/node-pre-gyp-github/bin/node-pre-gyp-github.js node-pre-gyp-github && npm run upload-binary
# deploy:
#   provider: npm
#   email: freestrings@gmail.com
#   api_key: $NPM_API_KEY
#   on:
#     branch: master